# ── llms.txt generator (v0.3) ─────────────────────────────────────────────────
#
# Generates a machine-readable llms.txt describing the *analyzed project*
# (its nodes, functions, and wiki summaries), not the explicaR package itself.
# The package's own llms.txt lives at inst/llms.txt.

#' Generate a project-level llms.txt reference file
#'
#' Produces a `llms.txt` (or custom path) summarising the analyzed project so
#' an LLM can quickly understand its structure without reading all source
#' files.  Includes: stats, file list, function index, key objects, wiki
#' summaries (when available), and the Mermaid dependency graph.
#'
#' @param project_dir Project directory. Default `"."`.
#' @param output_file Output path. Defaults to `<project_dir>/llms.txt`.
#' @param db_path Explicar DuckDB path. Defaults to `.explicar/explicar.duckdb`.
#' @param quiet Suppress progress messages. Default `FALSE`.
#'
#' @return Invisibly, the path to the written file.
#' @export
#'
#' @examples
#' \dontrun{
#' explicar_llms_txt("path/to/project")
#' # Then paste content into any LLM chat:
#' # cat(readLines("path/to/project/llms.txt"), sep = "\n")
#' }
explicar_llms_txt <- function(project_dir = ".",
                               output_file = NULL,
                               db_path     = NULL,
                               quiet       = FALSE) {

  project_dir <- normalizePath(project_dir, mustWork = TRUE)
  pkg_name    <- basename(project_dir)
  db_path     <- db_path %||% .explicar_db_path(project_dir)

  if (is.null(output_file)) output_file <- file.path(project_dir, "llms.txt")

  # Try to read code graph from DB, fall back to live parse
  nodes <- edges <- wiki_rows <- NULL
  if (file.exists(db_path) &&
      requireNamespace("duckdb", quietly = TRUE) &&
      requireNamespace("DBI",    quietly = TRUE)) {
    tryCatch({
      con <- DBI::dbConnect(duckdb::duckdb(), dbdir = db_path, read_only = TRUE)
      on.exit(DBI::dbDisconnect(con, shutdown = TRUE), add = TRUE)
      if (DBI::dbExistsTable(con, "nodes")) {
        nodes <- DBI::dbGetQuery(
          con, "SELECT name, type, file, line, label, shape_info FROM nodes ORDER BY type, name")
      }
      if (DBI::dbExistsTable(con, "edges")) {
        edges <- DBI::dbGetQuery(
          con, "SELECT from_node AS from, to_node AS to, type FROM edges LIMIT 500")
      }
      if (DBI::dbExistsTable(con, "wiki")) {
        wiki_rows <- DBI::dbGetQuery(
          con, "SELECT file, content FROM wiki ORDER BY file")
      }
    }, error = function(e) invisible())
  }

  # Live parse fallback
  if (is.null(nodes)) {
    pr    <- tryCatch(explicar_parse(project_dir), error = function(e) .empty_parse_result())
    nodes <- pr$nodes
    edges <- pr$edges
  }

  # Build the graph for the Mermaid section
  pr_for_graph <- tryCatch(
    explicar_parse(project_dir),
    error = function(e) .empty_parse_result()
  )

  out <- character(0L)

  # ── Header ────────────────────────────────────────────────────────────────
  out <- c(out,
    paste0("# ", pkg_name, " — LLM-readable codebase reference"),
    paste0("# Generated by explicaR ", format(Sys.Date(), "%Y-%m-%d")),
    paste0("# Project: ", project_dir),
    ""
  )

  # ── Stats ─────────────────────────────────────────────────────────────────
  n_nodes <- if (is.data.frame(nodes)) nrow(nodes) else 0L
  n_edges <- if (is.data.frame(edges)) nrow(edges) else 0L
  n_wiki  <- if (is.data.frame(wiki_rows)) nrow(wiki_rows) else 0L
  out <- c(out,
    "## Stats",
    "",
    paste0("nodes: ", n_nodes),
    paste0("edges: ", n_edges),
    paste0("wiki pages: ", n_wiki),
    ""
  )

  if (is.data.frame(nodes)) {
    # ── Scripts ───────────────────────────────────────────────────────────
    scripts <- nodes[nodes$type == "script", , drop = FALSE]
    if (nrow(scripts) > 0L) {
      out <- c(out, "## Source Files", "")
      out <- c(out, paste0("- ", scripts$name), "")
    }

    # ── Functions ─────────────────────────────────────────────────────────
    fns <- nodes[nodes$type == "function", , drop = FALSE]
    if (nrow(fns) > 0L) {
      out <- c(out, "## Functions", "")
      for (i in seq_len(nrow(fns))) {
        lbl <- fns$label[[i]]
        loc <- fns$file[[i]]
        ln  <- fns$line[[i]]
        desc <- if (!is.na(lbl) && lbl != fns$name[[i]]) paste0(" — ", lbl) else ""
        loc_str <- if (!is.na(loc)) paste0(" [", basename(loc), if (!is.na(ln)) paste0(":", ln) else "", "]") else ""
        out <- c(out, paste0("- `", fns$name[[i]], "()`", desc, loc_str))
      }
      out <- c(out, "")
    }

    # ── Variables ─────────────────────────────────────────────────────────
    vars <- nodes[nodes$type == "variable", , drop = FALSE]
    if (nrow(vars) > 0L) {
      out <- c(out, "## Key Objects", "")
      for (i in seq_len(nrow(vars))) {
        shape <- vars$shape_info[[i]]
        badge <- if (!is.na(shape) && nzchar(shape)) paste0(" (", shape, ")") else ""
        out <- c(out, paste0("- `", vars$name[[i]], "`", badge))
      }
      out <- c(out, "")
    }

    # ── Source files (CSV etc.) ────────────────────────────────────────────
    srcs <- nodes[nodes$type == "source", , drop = FALSE]
    if (nrow(srcs) > 0L) {
      out <- c(out, "## Data Sources", "")
      out <- c(out, paste0("- ", srcs$name), "")
    }
  }

  # ── Wiki summaries ─────────────────────────────────────────────────────────
  if (!is.null(wiki_rows) && nrow(wiki_rows) > 0L) {
    out <- c(out, "## File Summaries", "")
    for (i in seq_len(nrow(wiki_rows))) {
      fname   <- basename(wiki_rows$file[[i]])
      content <- wiki_rows$content[[i]]
      overview <- .llmstxt_section(content, "Overview")
      out <- c(out, paste0("### ", fname), "")
      if (nzchar(overview)) out <- c(out, overview, "")
    }
  }

  # ── Mermaid dependency graph ───────────────────────────────────────────────
  if (nrow(pr_for_graph$nodes) > 0L) {
    graph_text <- tryCatch(
      explicar_graph(pr_for_graph, direction = "LR"),
      error = function(e) ""
    )
    if (nzchar(graph_text)) {
      out <- c(out, "## Dependency Graph", "", "```mermaid", graph_text, "```", "")
    }
  }

  writeLines(out, output_file)
  if (!quiet) message("llms.txt written to: ", output_file)
  invisible(output_file)
}


# ── Helper ────────────────────────────────────────────────────────────────────

.llmstxt_section <- function(markdown, heading) {
  lines <- strsplit(markdown %||% "", "\n")[[1L]]
  start <- which(grepl(paste0("^#+\\s+", heading), lines, ignore.case = TRUE))
  if (!length(start)) return("")
  next_head <- which(grepl("^#+\\s+", lines) & seq_along(lines) > start[[1L]])
  end <- if (length(next_head)) next_head[[1L]] - 1L else length(lines)
  trimws(paste(lines[(start[[1L]] + 1L):end], collapse = "\n"))
}
